### ISSUE TITLE
Use Discord relative time in daily command

### ISSUE THREAD

**Issue by tacheometry** [crimsobot/crimsoBOT#144]
https://github.com/crimsobot/crimsoBOT/blob/master/crimsobot/utils/games.py#L106

The time format can be changed to `<t:0:t>` (which displays `12:00 AM` for someone in GMT). Or, to do it relatively, just calculate the difference in seconds and place it in `<t:diff:R>` (which would display something like `in 2 hours`).

Cool site which shows all Discord time formats: https://hammertime.cyou

**Comment by h-anjru** [comment]
This makes for a very good feature request! But since this is not an issue (i.e., does not address some broken functionality of the bot), I am closing this.

**Comment by williammck** [comment]
tagging properly and reopening, sorry for the confusion

**Comment by h-anjru** [comment]
So feature requests can be issues! Shows what I know!
