### ISSUE TITLE
Stop implicitly closing Pillow images

### ISSUE THREAD

**Issue by williammck** [crimsobot/crimsoBOT#7]
In v6.1.0 of Pillow, [`Image.__del__` was deprecated](https://pillow.readthedocs.io/en/stable/releasenotes/6.1.0.html#image-del).
We should be using a context manager or explicitly closing the file anyway to avoid memory leaks...

**Acceptance Criteria:**
- Deprecated functionality is no longer used.

**Comment by kel5isgod** [comment]
Searching through code that I'd expect uses pillow, such as cogs/images.py, I don't see any instances of __del__ with `Ctrl+F`. Any specific files? Has this issue already been fixed, and if so, should it be closed?

**Comment by williammck** [comment]
@kel5isgod `__del__` is called internally by Python when destroying objects - e.g. upon finishing execution of a method as part of garbage collection.
Right now, in some places, we're using `Image.open()` (or something similar?) but never actually closing the file - which means a find and replace won't easily pick it up.

**Comment by kel5isgod** [comment]
Oh, got it. I'll look into this and see what instances I can find. I wasn't quite aware of this.
